[package]
name = "impetus-impresario-server"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition = "2024"

[dependencies]
impetus-impresario-core = { workspace = true }
